spring:
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  datasource:
    url: jdbc:mysql://11
    username: root
    password: 11
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      max-lifetime: 1800000
      minimum-idle: 5
server:
  port: 5002

